name: WebdriverIO Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21]  # adjust based on your project

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run WebdriverIO tests
      run: npm run wdio  # or npx wdio run wdio.conf.js

    - name: Upload test report artifact
      uses: actions/upload-artifact@v4
      with:
        name: cucumber-json-report
        path: |
          report/json/
          report/cucumber-report.html
          screenshots/
